### PR TITLE
background image alpha value change

### PR DESCRIPTION
**Pull request by DirtBagXon**
Feel free to ignore, as it's a matter of personal preference.

But this stops the "ghost" brightness washout from the (fantastic) bright background image. 
Looks a little closer to the YouTube video available.... maybe......

### CODE REVIEW

**Comment by Widge-5** [comment]
Thanks @DirtBagXon. I appreciate the input.
I did look already look at adjusting the alpha value of the backdrop group, but this only serves to darken the static background image.  The overlaying animation elements will still be at full brightness when they appear.  Applying the same alpha value to those elements individually will balance them out but it also makes them semi transparent so the original image will be partly visible through the animated overlay - it is an alpha value not a brightness value. 
Do you know how to darken the elements without using an alpha transparency value?  I'm sure there must be a way.  I'd much prefer to handle it in the layout file rather than edit the images.
Thanks.

**Comment by DirtBagXon** [comment]
"_I'd much prefer to handle it in the layout file rather than edit the images._" - Yeah definitely the way to go, although playing with this I do notice that altering the alpha value does cause some overhead on the overall emulation speed in-game.

I was testing on a PC, so I think this overhead will probably be more evident on a Pi.

I am certainly no Mame artwork expert, but what you describe sounds like you would want a full screen overlay. Looking at docs: https://docs.mamedev.org/techspecs/layout_files.html#example-layout-files there may be some clues here....

We really need Mr Do! for some input here.....

**Comment by Widge-5** [comment]
That's a great idea.  I've played with coloured overlay elements before when I added some colour to Blue Shark.  I'll try that out soon.

**Comment by DirtBagXon** [comment]
Another option and seems to avoid the transparency issue, also not seeing the overhead using this route.

**Comment by Widge-5** [comment]
That's excellent, and it seems to apply the effect to the animated elements at the same time. 
How do you feel about dialling it back a little to 0.8?  Not so dark that it's too dim, but hopefully not overpoweringly bright at the same time?

**Comment by DirtBagXon** [comment]
I'll go with your suggestion but what about trying "0.75" first.

0.8 still seems a little too bright as the "Bubble Trouble" game title appears ?

**Comment by Widge-5** [comment]
That sounds good to me.  If you make the change I'll merge it. 👍

**Comment by DirtBagXon** [comment]
Updated, and added updated zip

**Pull request merged**
